sudo: required
language: minimal
install: skip

services:
  - docker

jobs:
  include:
    - stage: container creation
      script:
        - travis/containerCreation.sh

    - stage: release and tag on DockerHub
      if: tag =~ ^v[0-9.]*$
      deploy:
        provider: script
        script: travis/release.sh
        on:
          tags: true
      after_deploy:
        - travis/delete-dockerhub-images.sh

import:
  - docs/.travis.yml
# notifications:
#   slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#   email:
#     recipients:
#       - a.person@acme.com
#       - a.n.other@acme.com
#     on_success: never # default: change
#     on_failure: never # default: always
