sudo: required
language: minimal
install: skip

services:
  - docker

jobs:
  include:
    - stage: container creation and publishing
      script: travis/containerCreation.sh

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      script: travis/release.sh
      post_script: travis/delete-dockerhub-images.sh

import:
  - docs/.travis.yml
# notifications:
#   slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#   email:
#     recipients:
#       - a.person@acme.com
#       - a.n.other@acme.com
#     on_success: never # default: change
#     on_failure: never # default: always
