sudo: required
language: minimal
install: skip

services:
  - docker

jobs:
  include:
    - stage: container creation and publishing
      script: travis/containerCreation.sh

    - stage: release
      deploy:
        provider: script
        script: travis/release.sh
        on:
          tags: true
          condition: env(TRAVIS_TAG) =~ ^v[0-9.]*$
      after_deploy:
        - travis/delete-dockerhub-images.sh

import:
  - docs/.travis.yml
# notifications:
#   slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#   email:
#     recipients:
#       - a.person@acme.com
#       - a.n.other@acme.com
#     on_success: never # default: change
#     on_failure: never # default: always
